

#ifndef GROUP_AUGMENTATION_ATTRIBUTE_H
#define GROUP_AUGMENTATION_ATTRIBUTE_H

enum Attribute {
    ALPHA, ALPHA_AGE, BETA, BETA_AGE, DRIFT, DISPERSAL, HELP, SURVIVAL, AGE
};

#endif //GROUP_AUGMENTATION_ATTRIBUTE_H
