

#ifndef GROUP_AUGMENTATION_GENETYPE_H
#define GROUP_AUGMENTATION_GENETYPE_H

enum GeneType {
    ALPHA, ALPHA_AGE, BETA, BETA_AGE, DRIFT, DISPERSAL, HELP, SURVIVAL
};

#endif //GROUP_AUGMENTATION_GENETYPE_H
